Repository BrickSchema/brick-website, pull requests merged in 2019-08, with the labels that each got.

#44 Add webinar video to homepage
  gridsome.config.js
  webpages/about.md
Labels: content, enhancement

#47 fix the wrong version in schema files
  static/schema/1.0.3/Brick.ttl
  static/schema/1.0.3/BrickFrame.ttl
  static/schema/1.0.3/BrickTag.ttl
  static/schema/1.0.3/BrickUse.ttl
Labels: bug, priority: critical

#48 Update "Supporters" page
  src/layouts/Default.vue
  src/pages/Community.vue
  static/logos/research/cmu.png
  static/logos/research/ibm.png
  static/logos/research/sdu.png
  static/logos/research/ucb.png
  static/logos/research/ucla.png
  static/logos/research/ucsd.png
  static/logos/research/uva.png
  static/logos/supporters/doe.svg
  static/logos/supporters/ec.svg
  static/logos/supporters/ifd.png
  static/logos/supporters/intel.png
  static/logos/supporters/jci.png
  static/logos/supporters/kaust.svg
  static/logos/supporters/nsf.png
  static/logos/supporters/topas.png
  webpages/grants-and-awards.md
  webpages/supporters.md
Labels: content, enhancement, priority: high

#45 Concept Page
  webpages/concepts.md
  webpages/images/node-edge-graph.png
Labels: content, priority: critical
