Repository BrickSchema/brick-website, pull requests merged in 2019-07, with the labels that each got.

#29 Tree View for TagSets
  .gitignore
  gridsome.server.js
  src/components/RecursiveTree.vue
  src/components/TagSetSearchInput.vue
  src/templates/TagSet.vue
Labels: enhancement

#30 Docs compact
  src/components/RecursiveTree.vue
  src/templates/TagSet.vue
Labels: enhancement

#32 Getting started page refactorization
  webpages/get-started.md
Labels: content, enhancement, priority: critical

#35 Fix website serving path
  gridsome.server.js
  src/components/RecursiveTree.vue
  src/components/SearchInput.vue
  src/components/TagSetSearchInput.vue
Labels: bug, priority: critical

#38 Add travis integration
  .travis.yml
  README.md
  package.json
Labels: enhancement

#37 Restructuring the resources page
  webpages/downloads.md
  webpages/files/acm-e-energy-2019-portable-brick.pdf
  webpages/resources.md
Labels: content, priority: high
