Repository BrickSchema/brick-website, pull requests merged in 2020-06, with the labels that each got.

#75 Fix ontology search results
  src/components/OntologySearchInput.vue
Labels: bug, priority: high

#80 Adding relationship memo to Brick website
  ontologyPages/v1.1.md
  webpages/concepts.md
  webpages/get-started.md
  webpages/relationships.md
Labels: content, documentation, enhancement

#82 Add Bractlet, JCI to success stories section
  src/pages/Community.vue
  static/logos/success-stories/bractlet.png
Labels: content
