Repository BrickSchema/brick-website, pull requests merged in 2022-05, with the labels that each got.

#152 Add support for Turtle/SPARQL code blocks
  gridsome.config.js
  ontologyPages/v1.1.md
  package-lock.json
  package.json
  src/main.js
  usageDetails/timeseries.md
Labels: enhancement

#151 Add Brickly site
  tools/2022-05-12-brickly.md
  tools/images/brickly.png
Labels: content

#119 Updating Dependencies
  package-lock.json
Labels: dependencies
